#!/usr/bin/env bash
# =============================================================================
# GVD NVR — single-server Linux installer (Phase 7.4)
# =============================================================================
# Usage:
#   sudo ./install.sh           # interactive
#   sudo ./install.sh --quiet   # non-interactive (reads env vars)
#
# Reads from environment if --quiet:
#   NVR_ADMIN_EMAIL
#   NVR_ADMIN_PASSWORD
#   NVR_DB_PASSWORD
#   NVR_LICENSE_KEY        (optional)
#   NVR_STORAGE_PATH       (default: /var/lib/gvd-nvr/data)
#
# Steps:
#   1. check dependencies (docker, docker compose, openssl, ffmpeg-on-host
#      optional for go2rtc-less deployments)
#   2. prompt for values
#   3. write .env
#   4. docker compose pull + up -d
#   5. wait for migrate to finish
#   6. create systemd unit so the stack auto-starts at boot
#   7. print access URL + admin credentials
# =============================================================================

set -euo pipefail

QUIET=0
[[ "${1:-}" == "--quiet" ]] && QUIET=1

log()   { printf '\033[1;34m[install]\033[0m %s\n' "$*"; }
warn()  { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
fatal() { printf '\033[1;31m[error]\033[0m %s\n' "$*"; exit 1; }

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || fatal "$1 is required but not installed"
}

prompt() {
    local var="$1" prompt_msg="$2" default="${3:-}" secret="${4:-0}"
    local cur="${!var:-}"
    if [[ -n "$cur" ]]; then return; fi
    if (( QUIET )); then
        [[ -n "$default" ]] && printf -v "$var" '%s' "$default" || fatal "$var must be set in --quiet mode"
        return
    fi
    if (( secret )); then
        read -rsp "$prompt_msg${default:+ [$default]}: " value
        echo
    else
        read -rp "$prompt_msg${default:+ [$default]}: " value
    fi
    [[ -z "$value" ]] && value="$default"
    printf -v "$var" '%s' "$value"
}

# ── 1. Dependencies ─────────────────────────────────────────────────────────
log "Checking dependencies"
require_cmd docker
require_cmd openssl
docker compose version >/dev/null 2>&1 || fatal "docker compose v2 plugin not found"
docker_version=$(docker version --format '{{.Server.Version}}' 2>/dev/null || true)
log "Docker server: ${docker_version:-unknown}"

# ── 2. Prompts ──────────────────────────────────────────────────────────────
prompt NVR_ADMIN_EMAIL    "Admin email"                  "admin@example.com"
prompt NVR_ADMIN_PASSWORD "Admin password (>=12 chars)"  "" 1
prompt NVR_DB_PASSWORD    "Postgres password"            "$(openssl rand -hex 24)" 1
prompt NVR_LICENSE_KEY    "License key (optional)"       ""
prompt NVR_STORAGE_PATH   "Storage path on host"         "/var/lib/gvd-nvr/data"
prompt NVR_HTTP_PORT      "HTTP port"                    "80"
prompt NVR_HTTPS_PORT     "HTTPS port"                   "443"
prompt NVR_PUBLIC_HOST   "Public host/IP (for WebRTC)"  "$(hostname -I | awk '{print $1}')"

[[ ${#NVR_ADMIN_PASSWORD} -lt 12 ]] && fatal "Admin password must be >=12 chars"

# ── 3. Layout + .env ────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
log "Writing $ENV_FILE"
JWT_SECRET=$(openssl rand -hex 32)

mkdir -p "$NVR_STORAGE_PATH"

cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DB_USER=nvr
DB_PASSWORD=$NVR_DB_PASSWORD
JWT_SECRET_KEY=$JWT_SECRET
JWT_ACCESS_TOKEN_EXPIRE_HOURS=24
JWT_REFRESH_TOKEN_EXPIRE_DAYS=30
CORS_ORIGINS=https://localhost
HTTP_PORT=$NVR_HTTP_PORT
HTTPS_PORT=$NVR_HTTPS_PORT
STORAGE_HOST_PATH=$NVR_STORAGE_PATH
NVR_PUBLIC_HOST=$NVR_PUBLIC_HOST
GO2RTC_API_ORIGIN=https://$NVR_PUBLIC_HOST
GO2RTC_CANDIDATES=$NVR_PUBLIC_HOST:8555,127.0.0.1:8555
EOF
chmod 600 "$ENV_FILE"

# ── 3b. Generate go2rtc.yaml from template ──────────────────────────────────
log "Generating go2rtc.yaml"
if command -v python3 >/dev/null 2>&1; then
    NVR_PUBLIC_HOST="$NVR_PUBLIC_HOST" \
    GO2RTC_API_ORIGIN="https://$NVR_PUBLIC_HOST" \
    GO2RTC_CANDIDATES="$NVR_PUBLIC_HOST:8555,127.0.0.1:8555" \
    python3 "$SCRIPT_DIR/scripts/generate-go2rtc-config.py"
else
    warn "python3 not found — go2rtc.yaml will use defaults. Please edit manually."
fi

# ── 4. Pull + up ────────────────────────────────────────────────────────────
log "Pulling images"
docker compose -f "$SCRIPT_DIR/docker-compose.yml" pull
log "Running migrations"
docker compose -f "$SCRIPT_DIR/docker-compose.yml" run --rm migrate
log "Starting stack"
docker compose -f "$SCRIPT_DIR/docker-compose.yml" up -d

# ── 5. systemd unit ────────────────────────────────────────────────────────
if command -v systemctl >/dev/null 2>&1; then
    UNIT_PATH=/etc/systemd/system/gvd-nvr.service
    log "Installing systemd unit at $UNIT_PATH"
    cat > "$UNIT_PATH" <<EOF
[Unit]
Description=GVD NVR (docker compose)
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$SCRIPT_DIR
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable gvd-nvr.service
fi

# ── 6. Optional license install ─────────────────────────────────────────────
if [[ -n "$NVR_LICENSE_KEY" && -f "$NVR_LICENSE_KEY" ]]; then
    log "Installing license file"
    docker compose -f "$SCRIPT_DIR/docker-compose.yml" cp \
        "$NVR_LICENSE_KEY" backend:/data/certs/license.json
fi

# ── 7. Wait for backend then create admin user (via the first-run API) ─────
log "Waiting for backend to come up..."
for i in $(seq 1 30); do
    if curl -fsS http://localhost:8000/api/health >/dev/null 2>&1; then break; fi
    sleep 2
done

log "Creating admin user '$NVR_ADMIN_EMAIL'"
curl -fsS -X POST http://localhost:8000/api/auth/register \
    -H 'Content-Type: application/json' \
    -d "{\"username\":\"admin\",\"email\":\"$NVR_ADMIN_EMAIL\",\"password\":\"$NVR_ADMIN_PASSWORD\"}" \
    >/dev/null || warn "Admin user may already exist — skipping"

# ── 8. Done ────────────────────────────────────────────────────────────────
echo
log "Installation complete."
log "Access URL:    https://$(hostname -f 2>/dev/null || hostname)"
log "Admin user:    admin"
log "Admin email:   $NVR_ADMIN_EMAIL"
log "Storage path:  $NVR_STORAGE_PATH"
echo
log "Logs:  docker compose -f $SCRIPT_DIR/docker-compose.yml logs -f"
