#!/usr/bin/env bash
# =============================================================================
# GVD NVR — single-server Linux installer (Phase 7.4)
# =============================================================================
# See docs/INSTALL_LINUX.md for step-by-step instructions.
# Usage:
#   sudo ./install.sh                        # interactive (self-signed cert)
#   sudo ./install.sh --quiet                # non-interactive (reads env vars)
#   sudo ./install.sh --letsencrypt          # interactive + obtain LE cert
#   sudo ./install.sh --quiet --letsencrypt  # fully non-interactive + LE cert
#
# Additional env var for --letsencrypt:
#   NVR_LE_HOSTNAME   # public DNS hostname, e.g. nvr.example.com (required)
#
# Reads from environment if --quiet:
#   NVR_ADMIN_EMAIL
#   NVR_ADMIN_PASSWORD
#   NVR_DB_PASSWORD
#   NVR_LICENSE_KEY        (optional)
#   NVR_STORAGE_PATH       (default: /var/lib/gvd-nvr/data)
#
# Steps:
#   1. check dependencies (docker, docker compose, openssl, ffmpeg-on-host
#      optional for go2rtc-less deployments)
#   2. prompt for values
#   3. write .env
#   4. docker compose pull + up -d
#   5. wait for migrate to finish
#   6. create systemd unit so the stack auto-starts at boot
#   7. print access URL + admin credentials
# =============================================================================

set -euo pipefail

QUIET=0
LETSENCRYPT=0

for arg in "$@"; do
    case "$arg" in
        --quiet)       QUIET=1 ;;
        --letsencrypt) LETSENCRYPT=1 ;;
    esac
done

log()   { printf '\033[1;34m[install]\033[0m %s\n' "$*"; }
warn()  { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }
fatal() { printf '\033[1;31m[error]\033[0m %s\n' "$*"; exit 1; }

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || fatal "$1 is required but not installed"
}

prompt() {
    local var="$1" prompt_msg="$2" default="${3:-}" secret="${4:-0}"
    local cur="${!var:-}"
    if [[ -n "$cur" ]]; then return; fi
    if (( QUIET )); then
        [[ -n "$default" ]] && printf -v "$var" '%s' "$default" || fatal "$var must be set in --quiet mode"
        return
    fi
    if (( secret )); then
        read -rsp "$prompt_msg${default:+ [$default]}: " value
        echo
    else
        read -rp "$prompt_msg${default:+ [$default]}: " value
    fi
    [[ -z "$value" ]] && value="$default"
    printf -v "$var" '%s' "$value"
}

# ── 1. Dependencies ─────────────────────────────────────────────────────────
log "Checking dependencies"
require_cmd docker
require_cmd openssl
docker compose version >/dev/null 2>&1 || fatal "docker compose v2 plugin not found"
docker_version=$(docker version --format '{{.Server.Version}}' 2>/dev/null || true)
log "Docker server: ${docker_version:-unknown}"

# ── 2. Prompts ──────────────────────────────────────────────────────────────
prompt NVR_ADMIN_EMAIL    "Admin email"                  "admin@example.com"
prompt NVR_ADMIN_PASSWORD "Admin password (>=12 chars)"  "" 1
prompt NVR_DB_PASSWORD    "Postgres password"            "$(openssl rand -hex 24)" 1
prompt NVR_LICENSE_KEY    "License key (optional)"       ""
prompt NVR_STORAGE_PATH   "Storage path on host"         "/var/lib/gvd-nvr/data"
prompt NVR_HTTP_PORT      "HTTP port"                    "80"
prompt NVR_HTTPS_PORT     "HTTPS port"                   "443"
# Portable host IP detection (works on Linux, macOS, and minimal distros)
_detect_host_ip() {
    local ip=""
    if command -v ip >/dev/null 2>&1; then
        ip=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") {print $(i+1); exit}}')
    fi
    if [[ -z "$ip" ]] && command -v hostname >/dev/null 2>&1; then
        ip=$(hostname -I 2>/dev/null | awk '{print $1}')
    fi
    if [[ -z "$ip" ]]; then
        ip=$(ifconfig 2>/dev/null | awk '/inet / {print $2; exit}' | sed 's/addr://')
    fi
    echo "${ip:-127.0.0.1}"
}
prompt NVR_PUBLIC_HOST   "Public host/IP (for WebRTC)"  "$(_detect_host_ip)"

# Let's Encrypt: if --letsencrypt flag is set, prompt for the public hostname
if (( LETSENCRYPT )); then
    prompt NVR_LE_HOSTNAME "Public hostname for Let's Encrypt cert (e.g. nvr.example.com)" ""
    [[ -z "${NVR_LE_HOSTNAME:-}" ]] && fatal "NVR_LE_HOSTNAME is required for --letsencrypt"
fi

[[ ${#NVR_ADMIN_PASSWORD} -lt 12 ]] && fatal "Admin password must be >=12 chars"

# ── 3. Layout + .env ────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
log "Writing $ENV_FILE"

# Preserve existing JWT secret so re-running the installer doesn't invalidate
# all sessions, refresh tokens, and API keys.
if [[ -f "$ENV_FILE" ]]; then
    EXISTING_JWT=$(grep '^JWT_SECRET_KEY=' "$ENV_FILE" 2>/dev/null | cut -d= -f2-)
fi
JWT_SECRET=${EXISTING_JWT:-$(openssl rand -hex 32)}
if [[ -n "${EXISTING_JWT:-}" ]]; then
    log "Preserved existing JWT_SECRET_KEY from $ENV_FILE"
fi

mkdir -p "$NVR_STORAGE_PATH"

cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DB_USER=nvr
DB_PASSWORD=$NVR_DB_PASSWORD
JWT_SECRET_KEY=$JWT_SECRET
JWT_ACCESS_TOKEN_EXPIRE_HOURS=24
JWT_REFRESH_TOKEN_EXPIRE_DAYS=30
CORS_ORIGINS=https://$NVR_PUBLIC_HOST,http://$NVR_PUBLIC_HOST,https://localhost,http://localhost
HTTP_PORT=$NVR_HTTP_PORT
HTTPS_PORT=$NVR_HTTPS_PORT
STORAGE_HOST_PATH=$NVR_STORAGE_PATH
NVR_PUBLIC_HOST=$NVR_PUBLIC_HOST
GO2RTC_API_ORIGIN=https://$NVR_PUBLIC_HOST
GO2RTC_CANDIDATES=$NVR_PUBLIC_HOST:8555,127.0.0.1:8555
EOF
chmod 600 "$ENV_FILE"

# ── 3b. Generate go2rtc.yaml from template ──────────────────────────────────
log "Generating go2rtc.yaml"
if command -v python3 >/dev/null 2>&1; then
    NVR_PUBLIC_HOST="$NVR_PUBLIC_HOST" \
    GO2RTC_API_ORIGIN="https://$NVR_PUBLIC_HOST" \
    GO2RTC_CANDIDATES="$NVR_PUBLIC_HOST:8555,127.0.0.1:8555" \
    python3 "$SCRIPT_DIR/scripts/generate-go2rtc-config.py"
else
    warn "python3 not found — go2rtc.yaml will use defaults. Please edit manually."
fi

# ── 4. Pull + up ────────────────────────────────────────────────────────────
log "Seeding go2rtc config from template"
bash "$SCRIPT_DIR/scripts/seed-go2rtc-config.sh"
log "Pulling images"
docker compose -f "$SCRIPT_DIR/docker-compose.yml" pull
log "Running migrations"
docker compose -f "$SCRIPT_DIR/docker-compose.yml" run --rm migrate
log "Starting stack"
docker compose -f "$SCRIPT_DIR/docker-compose.yml" up -d

# ── 5. systemd unit ────────────────────────────────────────────────────────
if command -v systemctl >/dev/null 2>&1; then
    UNIT_PATH=/etc/systemd/system/gvd-nvr.service
    log "Installing systemd unit at $UNIT_PATH"
    cat > "$UNIT_PATH" <<EOF
[Unit]
Description=GVD NVR (docker compose)
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$SCRIPT_DIR
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable gvd-nvr.service
fi

# ── 5b. Let's Encrypt TLS certificate ──────────────────────────────────────
if (( LETSENCRYPT )); then
    log "Obtaining Let's Encrypt certificate for $NVR_LE_HOSTNAME"

    # Ensure certbot is installed
    if ! command -v certbot >/dev/null 2>&1; then
        fatal "certbot is not installed. Install it first:
  Ubuntu/Debian:  sudo apt-get install -y certbot
  CentOS/RHEL:    sudo yum install -y certbot
  Then re-run:    sudo ./install.sh --letsencrypt"
    fi

    # Port 80 must be free briefly for standalone challenge.
    # Stop nginx if it's running on port 80.
    if docker compose ps nginx 2>/dev/null | grep -q "Up"; then
        log "Stopping nginx temporarily for ACME challenge..."
        docker compose stop nginx
        _NGINX_WAS_RUNNING=1
    fi

    certbot certonly --standalone \
        --non-interactive \
        --agree-tos \
        --email "${NVR_ADMIN_EMAIL}" \
        -d "${NVR_LE_HOSTNAME}" \
        || fatal "certbot failed. Ensure port 80 is open and ${NVR_LE_HOSTNAME} resolves to this server's public IP."

    # Copy cert + key into the certs Docker volume (mounted at /certs in nginx)
    CERT_SRC="/etc/letsencrypt/live/${NVR_LE_HOSTNAME}"
    NGINX_CERT_DIR="$SCRIPT_DIR/nginx/certs"
    mkdir -p "$NGINX_CERT_DIR"
    cp -f "${CERT_SRC}/fullchain.pem" "$NGINX_CERT_DIR/server.crt"
    cp -f "${CERT_SRC}/privkey.pem"   "$NGINX_CERT_DIR/server.key"
    chmod 600 "$NGINX_CERT_DIR/server.key"
    log "Let's Encrypt cert written to $NGINX_CERT_DIR"

    # Update .env with public hostname
    sed -i "s|^CORS_ORIGINS=.*|CORS_ORIGINS=https://${NVR_LE_HOSTNAME},https://localhost|" "$ENV_FILE"
    sed -i "s|^NVR_PUBLIC_HOST=.*|NVR_PUBLIC_HOST=${NVR_LE_HOSTNAME}|" "$ENV_FILE"
    log "Updated CORS_ORIGINS and NVR_PUBLIC_HOST in $ENV_FILE to $NVR_LE_HOSTNAME"

    # Restart nginx if we stopped it
    if [[ "${_NGINX_WAS_RUNNING:-0}" == "1" ]]; then
        docker compose start nginx
    fi

    # Install auto-renewal cron entry
    RENEW_HOOK="docker compose -f $SCRIPT_DIR/docker-compose.yml exec nginx nginx -s reload"
    CRON_LINE="0 3 * * * certbot renew --quiet --post-hook \"$RENEW_HOOK\""
    CRON_FILE="/etc/cron.d/gvd-nvr-certbot"
    echo "$CRON_LINE" > "$CRON_FILE"
    chmod 644 "$CRON_FILE"
    log "Auto-renewal cron installed at $CRON_FILE"
    log "Cert will renew daily at 03:00 and nginx will reload automatically."
fi

# ── 6. Optional license install ─────────────────────────────────────────────
if [[ -n "$NVR_LICENSE_KEY" && -f "$NVR_LICENSE_KEY" ]]; then
    log "Installing license file"
    docker compose -f "$SCRIPT_DIR/docker-compose.yml" cp \
        "$NVR_LICENSE_KEY" backend:/data/certs/license.json
fi

# ── 7. Wait for backend then create admin user (via the first-run API) ─────
log "Waiting for backend to come up (max 90s)..."
ADMIN_CREATED=0
for i in $(seq 1 45); do
    if curl -fsS http://localhost:8000/api/health >/dev/null 2>&1; then
        log "Backend healthy — creating admin user '$NVR_ADMIN_EMAIL'"
        if curl -fsS -X POST http://localhost:8000/api/auth/register \
            -H 'Content-Type: application/json' \
            -d "{\"username\":\"admin\",\"email\":\"$NVR_ADMIN_EMAIL\",\"password\":\"$NVR_ADMIN_PASSWORD\"}" \
            >/dev/null 2>&1; then
            ADMIN_CREATED=1
            log "Admin user created successfully"
        else
            warn "Admin user may already exist — skipping registration"
        fi
        break
    fi
    sleep 2
done

if [[ $ADMIN_CREATED -eq 0 && $i -eq 45 ]]; then
    fatal "Backend did not become healthy within 90s. Check logs: docker compose -f $SCRIPT_DIR/docker-compose.yml logs backend"
fi

# ── 8. Done ────────────────────────────────────────────────────────────────
echo
log "Installation complete."
log "Access URL:    https://$(hostname -f 2>/dev/null || hostname)"
log "Admin user:    admin"
log "Admin email:   $NVR_ADMIN_EMAIL"
log "Storage path:  $NVR_STORAGE_PATH"
echo
log "Uninstall:     $SCRIPT_DIR/scripts/uninstall.sh"
log "Logs:          docker compose -f $SCRIPT_DIR/docker-compose.yml logs -f"
