#Requires -Version 5.1
# =============================================================================
# GVD NVR — Windows installer (PowerShell)
# =============================================================================
# See install.sh for the Linux/macOS equivalent.
#
# Usage (interactive):
#   Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
#   .\install.ps1
#
# Usage (non-interactive / CI):
#   $env:NVR_ADMIN_EMAIL    = "admin@example.com"
#   $env:NVR_ADMIN_PASSWORD = "SuperSecret123!"
#   .\install.ps1 -Quiet
#
# Requirements:
#   - Docker Desktop >= 4.x  (with WSL 2 backend recommended)
#     https://docs.docker.com/desktop/install/windows-install/
#   - File sharing enabled for the drive that contains this repo
#     (Docker Desktop > Settings > Resources > File Sharing)
# =============================================================================

param(
    [switch]$Quiet
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# ── Helpers ──────────────────────────────────────────────────────────────────

function Log   { param([string]$Msg) Write-Host "[install] $Msg" -ForegroundColor Cyan }
function Warn  { param([string]$Msg) Write-Host "[warn]    $Msg" -ForegroundColor Yellow }
function Fatal { param([string]$Msg) Write-Host "[error]   $Msg" -ForegroundColor Red; exit 1 }

function Prompt-Value {
    param(
        [string]$EnvVar,
        [string]$PromptMsg,
        [string]$Default = '',
        [switch]$Secret
    )
    $cur = [System.Environment]::GetEnvironmentVariable($EnvVar)
    if (-not [string]::IsNullOrEmpty($cur)) { return $cur }
    if ($Quiet) {
        if ([string]::IsNullOrEmpty($Default)) { Fatal "$EnvVar must be set when running -Quiet" }
        return $Default
    }
    $hint = if ($Default) { " [$Default]" } else { '' }
    if ($Secret) {
        $ss = Read-Host -Prompt "$PromptMsg$hint" -AsSecureString
        $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($ss)
        $val = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr)
        [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    } else {
        $val = Read-Host -Prompt "$PromptMsg$hint"
    }
    if ([string]::IsNullOrEmpty($val)) { $val = $Default }
    return $val
}

function Random-Secret { param([int]$Bytes = 32)
    $data = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($data)
    return [System.BitConverter]::ToString($data) -replace '-',''
}

# ── 1. Dependencies ───────────────────────────────────────────────────────────

Log "Checking dependencies"

# Docker
$dockerCmd = Get-Command docker -ErrorAction SilentlyContinue
if (-not $dockerCmd) {
    Fatal ("Docker is not installed or not in PATH.`n" +
           "Install Docker Desktop from: https://docs.docker.com/desktop/install/windows-install/`n" +
           "Then restart this terminal and re-run install.ps1")
}

# docker compose v2
try {
    $null = docker compose version 2>&1
} catch {
    Fatal ("'docker compose' (v2 plugin) not found.`n" +
           "Upgrade Docker Desktop to >= 4.x which bundles the compose plugin.")
}

$dockerVer = (docker version --format '{{.Server.Version}}' 2>$null)
Log "Docker server: $dockerVer"

# ── 2. Prompts ───────────────────────────────────────────────────────────────

$defaultDbPass  = Random-Secret -Bytes 24
$defaultJwtSec  = Random-Secret -Bytes 32
$defaultIp      = (Get-NetIPAddress -AddressFamily IPv4 |
                   Where-Object { $_.InterfaceAlias -notmatch 'Loopback' } |
                   Select-Object -First 1).IPAddress

$NVR_ADMIN_EMAIL    = Prompt-Value 'NVR_ADMIN_EMAIL'    'Admin email'                    'admin@example.com'
$NVR_ADMIN_PASSWORD = Prompt-Value 'NVR_ADMIN_PASSWORD' 'Admin password (>=12 chars)'    ''           -Secret
$NVR_DB_PASSWORD    = Prompt-Value 'NVR_DB_PASSWORD'    'Postgres password'              $defaultDbPass -Secret
$NVR_LICENSE_KEY    = Prompt-Value 'NVR_LICENSE_KEY'    'License key file path (optional)' ''
$NVR_STORAGE_PATH   = Prompt-Value 'NVR_STORAGE_PATH'   'Storage path on host'           'C:\gvd-nvr\data'
$NVR_HTTP_PORT      = Prompt-Value 'NVR_HTTP_PORT'      'HTTP port'                      '80'
$NVR_HTTPS_PORT     = Prompt-Value 'NVR_HTTPS_PORT'     'HTTPS port'                     '443'
$NVR_PUBLIC_HOST    = Prompt-Value 'NVR_PUBLIC_HOST'    'Public host/IP (for WebRTC)'    ($defaultIp ?? '127.0.0.1')

if ($NVR_ADMIN_PASSWORD.Length -lt 12) {
    Fatal "Admin password must be at least 12 characters"
}

# ── 3. Write .env ─────────────────────────────────────────────────────────────

$EnvFile = Join-Path $ScriptDir '.env'
Log "Writing $EnvFile"

$timestamp = (Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')
$envContent = @"
# Generated by install.ps1 on $timestamp
DB_USER=nvr
DB_PASSWORD=$NVR_DB_PASSWORD
JWT_SECRET_KEY=$defaultJwtSec
JWT_ACCESS_TOKEN_EXPIRE_HOURS=24
JWT_REFRESH_TOKEN_EXPIRE_DAYS=30
CORS_ORIGINS=https://localhost
HTTP_PORT=$NVR_HTTP_PORT
HTTPS_PORT=$NVR_HTTPS_PORT
STORAGE_HOST_PATH=$NVR_STORAGE_PATH
NVR_PUBLIC_HOST=$NVR_PUBLIC_HOST
GO2RTC_API_ORIGIN=https://$NVR_PUBLIC_HOST
GO2RTC_CANDIDATES=$NVR_PUBLIC_HOST`:8555,127.0.0.1:8555
"@

Set-Content -Path $EnvFile -Value $envContent -Encoding UTF8
# Restrict permissions (owner-only read/write)
$acl = Get-Acl $EnvFile
$acl.SetAccessRuleProtection($true, $false)
$rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
    'FullControl', 'Allow')
$acl.AddAccessRule($rule)
Set-Acl $EnvFile $acl

# ── 3b. Seed go2rtc.yaml ─────────────────────────────────────────────────────

Log "Seeding go2rtc.yaml from template"
& "$ScriptDir\scripts\seed-go2rtc-config.ps1"

# ── 3c. TLS certificate (self-signed) ─────────────────────────────────────────
# We generate a self-signed cert in the Windows cert store and export PEM
# files so nginx can use them.  If export fails (requires elevated session),
# we skip and warn the user.

$CertDir  = Join-Path $ScriptDir 'nginx\certs'
$CertFile = Join-Path $CertDir 'server.crt'
$KeyFile  = Join-Path $CertDir 'server.key'

if (-not (Test-Path $CertFile)) {
    Log "Generating self-signed TLS certificate"
    try {
        if (-not (Test-Path $CertDir)) { New-Item -ItemType Directory -Path $CertDir | Out-Null }

        $cert = New-SelfSignedCertificate `
            -DnsName $NVR_PUBLIC_HOST, 'localhost' `
            -CertStoreLocation 'Cert:\CurrentUser\My' `
            -KeyExportPolicy Exportable `
            -NotAfter (Get-Date).AddYears(5) `
            -KeyAlgorithm RSA `
            -KeyLength 2048

        # Export PFX then convert to PEM via openssl (if available) or raw export
        $pfxPath = Join-Path $env:TEMP 'nvr_tmp.pfx'
        $pfxPwd  = ConvertTo-SecureString -String 'nvrtmp' -Force -AsPlainText
        Export-PfxCertificate -Cert $cert -FilePath $pfxPath -Password $pfxPwd | Out-Null

        $opensslCmd = Get-Command openssl -ErrorAction SilentlyContinue
        if ($opensslCmd) {
            openssl pkcs12 -in $pfxPath -nokeys -clcerts -out $CertFile -password pass:nvrtmp 2>$null
            openssl pkcs12 -in $pfxPath -nocerts -nodes  -out $KeyFile  -password pass:nvrtmp 2>$null
            Remove-Item $pfxPath -Force
            Log "TLS cert written to $CertDir"
        } else {
            Warn ("openssl not found in PATH — cannot convert PFX to PEM.`n" +
                  "Options:`n" +
                  "  A) Install Git for Windows (includes openssl) and re-run install.ps1`n" +
                  "  B) Install openssl from https://slproweb.com/products/Win32OpenSSL.html`n" +
                  "  C) Use the PFX at $pfxPath manually`n" +
                  "The stack will start but HTTPS may not work until certs are in $CertDir")
        }
    } catch {
        Warn "Could not generate self-signed cert: $_"
        Warn "The stack will start. Add PEM certs to $CertDir to enable HTTPS."
    }
} else {
    Log "TLS cert already exists at $CertFile — skipping"
}

# ── 4. Create storage path ────────────────────────────────────────────────────

if (-not (Test-Path $NVR_STORAGE_PATH)) {
    New-Item -ItemType Directory -Path $NVR_STORAGE_PATH -Force | Out-Null
    Log "Created storage path: $NVR_STORAGE_PATH"
}

# ── 5. docker compose up ──────────────────────────────────────────────────────

Log "Pulling images (this may take a few minutes on first run)"
docker compose -f "$ScriptDir\docker-compose.yml" pull

Log "Running database migrations"
docker compose -f "$ScriptDir\docker-compose.yml" run --rm migrate

Log "Starting stack"
docker compose -f "$ScriptDir\docker-compose.yml" up -d --build

# ── 6. Health wait ────────────────────────────────────────────────────────────

Log "Waiting for backend to be ready..."
$maxAttempts = 30
$attempt = 0
$ready = $false
while ($attempt -lt $maxAttempts) {
    try {
        $resp = Invoke-WebRequest -Uri 'http://localhost:8000/api/health' -UseBasicParsing -TimeoutSec 3 -ErrorAction SilentlyContinue
        if ($resp.StatusCode -eq 200) { $ready = $true; break }
    } catch {}
    Start-Sleep -Seconds 2
    $attempt++
}

if (-not $ready) {
    Warn "Backend did not respond after $($maxAttempts * 2) seconds."
    Warn "Check logs: docker compose logs -f backend"
}

# ── 7. Create admin user ──────────────────────────────────────────────────────

if ($ready) {
    Log "Creating admin user '$NVR_ADMIN_EMAIL'"
    $body = @{
        username = 'admin'
        email    = $NVR_ADMIN_EMAIL
        password = $NVR_ADMIN_PASSWORD
    } | ConvertTo-Json

    try {
        Invoke-RestMethod -Method Post `
            -Uri 'http://localhost:8000/api/auth/register' `
            -ContentType 'application/json' `
            -Body $body | Out-Null
    } catch {
        Warn "Admin user may already exist — skipping registration"
    }
}

# ── 8. Optional license install ───────────────────────────────────────────────

if (-not [string]::IsNullOrEmpty($NVR_LICENSE_KEY) -and (Test-Path $NVR_LICENSE_KEY)) {
    Log "Installing license file"
    docker compose -f "$ScriptDir\docker-compose.yml" cp `
        "$NVR_LICENSE_KEY" backend:/data/certs/license.json
}

# ── 9. Done ───────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  GVD NVR — installation complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Log "Access URL:    https://localhost:$NVR_HTTPS_PORT"
Log "Admin user:    admin"
Log "Admin email:   $NVR_ADMIN_EMAIL"
Log "Admin passwd:  (the one you entered)"
Log "Storage path:  $NVR_STORAGE_PATH"
Write-Host ""
Log "Manage the stack with: .\bin\nvr.ps1 <up|down|logs|rebuild|migrate>"
Log "Logs:  docker compose logs -f"
Write-Host ""
Write-Host "NOTE: Your browser will warn about the self-signed certificate." -ForegroundColor Yellow
Write-Host "      Click 'Advanced' → 'Proceed to localhost' to continue."    -ForegroundColor Yellow
Write-Host ""
