"""Configuration package — re-exports every setting from settings.py so call
sites keep using `import config; config.X` (or `from config import X`)."""
from .settings import *  # noqa: F401,F403
from . import settings  # noqa: F401

# Re-export module-level names explicitly for `config.X` attribute access.
from .settings import (  # noqa: F401
    PORT, SCENARIO_SLUG, VIZOR_BASE_URL, VIZOR_API_KEY, VIZOR_SERVICE_TOKEN,
    FRS_DATABASE_URL, DATA_PATH, QDRANT_URL, QDRANT_COLLECTION,
    INFERENCE_BACKEND, TRITON_URL, DETECTOR_MODEL_PATH, EMBED_MODEL_PATH, ANTISPOOF_MODEL_PATH,
    FRAME_INTERVAL_SECONDS, MAX_SCAN_FRAMES,
    DET_CONF_THRESHOLD, SIMILARITY_THRESHOLD, DUPLICATE_COSINE,
    ENROLL_MIN_FACE_PX, ENROLL_MAX_POSE_DEG, ENROLL_MIN_SHARPNESS,
    VECTOR_SIZE, MAX_PHOTO_BYTES, ALLOWED_CONTENT, VERSION, MANIFEST_PATH,
    LIVE_ENABLED, GO2RTC_RTSP_HOST, GO2RTC_RTSP_PORT, LIVE_POLL_SECONDS,
    LIVE_DEFAULT_FPS, LIVE_ALERT_COOLDOWN, LIVE_USE_SUBSTREAM,
    FAIRFACE_MODEL_PATH, LIVENESS_THRESHOLD,
    LIVE_MIN_FACE_PX, LIVE_MAX_POSE_DEG, LIVE_MIN_SHARPNESS, LIVE_DET_CONF,
    LIVE_VOTE_MIN_FRAMES, LIVE_HIGH_CONF_SCORE, LIVE_MOTION_BLUR_MAX_DISP_RATIO,
)
