# =============================================================================
# Vendor Ed25519 public key — used by every install to verify .lic files.
#
# Private key lives OFF the deploy host. License files are generated by
# scripts/sign_license.py (vendor side) and uploaded by customer through
# the Settings → License page.
#
# IMPORTANT: rotating this key invalidates every previously-issued license.
# =============================================================================

import base64
import os

# 32-byte raw Ed25519 public key, base64-encoded.
# Override via env LICENSE_PUBLIC_KEY for staging / different signing trees.
VENDOR_PUBLIC_KEY_B64 = os.getenv(
    "LICENSE_PUBLIC_KEY",
    # Default dev key — paired with vendor-keys/private.pem generated by
    # scripts/sign_license.py keygen. Replace via LICENSE_PUBLIC_KEY env in
    # production with the customer-facing signing tree.
    "MCowBQYDK2VwAyEADRkzsd1Xaxj2/zmTvrN2EFgj5tkbgIVBb5Rujvrcx4k=",
)


def load_public_key():
    from cryptography.hazmat.primitives.serialization import load_der_public_key

    raw = base64.b64decode(VENDOR_PUBLIC_KEY_B64)
    return load_der_public_key(raw)
