"""baseline anpr schema

Creates the full ANPR schema for a fresh database (anpr_plate_reads,
anpr_plate_list, anpr_settings). Idempotent (checkfirst) so it is safe on an
existing pre-Alembic install — those are stamped to this revision rather than
re-running it. Later schema changes get their own autogenerated migrations.

Revision ID: anpr_0001_baseline
Revises:
Create Date: 2026-06-21
"""
from alembic import op

from db.models import Base

revision = "anpr_0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(op.get_bind(), checkfirst=True)


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
