// =============================================================================
// Settings · License — /settings/license
// =============================================================================
// Shows current license status + usage bars. Admin uploads a .lic file
// generated by the vendor signing tool.
// =============================================================================

import React, { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ShieldCheck,
  ShieldAlert,
  UploadCloud,
  Trash2,
  Cpu,
  Camera,
  Calendar,
} from "lucide-react";
import { toast } from "sonner";
import {
  getLicense,
  getFingerprint,
  activateLicense,
  clearLicense,
} from "../../api/license";
import { friendlyError } from "../../lib/utils";

// Map raw backend license `reason` codes to clean operator-facing labels.
// Never render the raw code (some carry "load_error:<exception>" internals).
const REASON_LABELS = {
  no_license_installed: "No license",
  missing_expires_at: "Invalid license",
  expired: "Expired",
  in_grace_period: "In grace period",
  hardware_mismatch: "Wrong machine",
};

const reasonLabel = (reason) => {
  if (!reason) return "Inactive";
  if (REASON_LABELS[reason]) return REASON_LABELS[reason];
  // Unknown / structured codes (e.g. "load_error:…") must not leak internals.
  return "Invalid license";
};

// ─── Shared primitives ────────────────────────────────────────────────────────

const PrimaryBtn = ({ children, disabled, onClick, type = "button" }) => (
  <button
    type={type}
    onClick={onClick}
    disabled={disabled}
    className="inline-flex items-center h-[28px] px-3 rounded font-telemetry text-[11px] font-semibold uppercase tracking-wide transition-opacity disabled:opacity-50"
    style={{ background: "var(--console-accent)", color: "#06231f" }}
  >
    {children}
  </button>
);

const SecondaryBtn = ({ children, disabled, onClick, type = "button" }) => (
  <button
    type={type}
    onClick={onClick}
    disabled={disabled}
    className="inline-flex items-center h-[28px] px-3 rounded font-telemetry text-[11px] border transition-colors hover:bg-white/5 disabled:opacity-50"
    style={{
      background: "var(--console-raised)",
      borderColor: "var(--console-border)",
      color: "var(--console-muted)",
    }}
  >
    {children}
  </button>
);

const ConsoleCard = ({ children, className = "" }) => (
  <div
    className={`rounded p-4 ${className}`}
    style={{
      background: "var(--console-panel)",
      border: "1px solid var(--console-border)",
    }}
  >
    {children}
  </div>
);

// ─── Stat Bar ────────────────────────────────────────────────────────────────

const StatBar = ({ label, used, limit, icon: Icon }) => {
  const pct = limit > 0 ? Math.min(100, (used / limit) * 100) : 0;
  const hot = pct >= 90;
  return (
    <ConsoleCard>
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          {Icon && <Icon className="h-3.5 w-3.5" style={{ color: "var(--console-muted)" }} />}
          <span
            className="font-telemetry text-[10px] uppercase tracking-widest"
            style={{ color: "var(--console-muted)" }}
          >
            {label}
          </span>
        </div>
        <span
          className="font-telemetry text-xs"
          style={{ color: hot ? "var(--console-rec)" : "var(--console-text)" }}
        >
          {used} / {limit || "∞"}
        </span>
      </div>
      <div
        className="h-1 rounded-full overflow-hidden"
        style={{ background: "var(--console-raised)" }}
      >
        <div
          className="h-full rounded-full"
          style={{
            width: `${pct}%`,
            background: hot ? "var(--console-rec)" : "var(--console-accent)",
          }}
        />
      </div>
    </ConsoleCard>
  );
};

// ─── Confirm Clear Dialog ────────────────────────────────────────────────────

const ConfirmDialog = ({ open, onConfirm, onCancel, isPending }) => {
  if (!open) return null;
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center"
      style={{ background: "rgba(0,0,0,0.7)" }}
    >
      <div
        className="rounded p-6 max-w-sm w-full mx-4"
        style={{
          background: "var(--console-panel)",
          border: "1px solid var(--console-border)",
        }}
      >
        <p
          className="font-telemetry text-xs font-semibold uppercase tracking-wide mb-2"
          style={{ color: "var(--console-text)" }}
        >
          Remove license?
        </p>
        <p
          className="font-telemetry text-[11px] mb-5"
          style={{ color: "var(--console-muted)" }}
        >
          The .lic file will be deleted. The platform will be disabled —
          cameras, recording, and all features stop until a valid license is
          uploaded again.
        </p>
        <div className="flex gap-2 justify-end">
          <SecondaryBtn onClick={onCancel}>Cancel</SecondaryBtn>
          <button
            onClick={onConfirm}
            disabled={isPending}
            className="inline-flex items-center h-[28px] px-3 rounded font-telemetry text-[11px] font-semibold uppercase tracking-wide disabled:opacity-50"
            style={{ background: "var(--console-rec)", color: "#fff" }}
          >
            Remove
          </button>
        </div>
      </div>
    </div>
  );
};

// ─── Main Page ────────────────────────────────────────────────────────────────

const LicensePage = () => {
  const qc = useQueryClient();
  const inputRef = useRef(null);
  const [confirmClear, setConfirmClear] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ["license"],
    queryFn: getLicense,
  });

  const { data: fp } = useQuery({
    queryKey: ["license-fingerprint"],
    queryFn: getFingerprint,
  });

  const activateMut = useMutation({
    mutationFn: activateLicense,
    onSuccess: () => {
      toast.success("License activated");
      qc.invalidateQueries({ queryKey: ["license"] });
    },
    onError: (e) => {
      // The activate endpoint returns clean, operator-fixable 400 detail
      // strings ("License is for a different machine", "License has expired").
      // Surface those directly; otherwise a generic, non-technical message.
      const detail = e?.response?.data?.detail;
      const status = e?.response?.status;
      toast.error(
        status === 400 && typeof detail === "string" && detail
          ? detail
          : friendlyError(e, "Couldn't activate that license file."),
      );
    },
  });

  const clearMut = useMutation({
    mutationFn: clearLicense,
    onSuccess: () => {
      toast.success("License cleared");
      qc.invalidateQueries({ queryKey: ["license"] });
      setConfirmClear(false);
    },
    onError: (e) =>
      toast.error(friendlyError(e, "Couldn't remove the license.")),
  });

  const onPick = (e) => {
    const f = e.target.files?.[0];
    if (!f) return;
    activateMut.mutate(f);
    e.target.value = "";
  };

  const copyFingerprint = () => {
    if (!fp?.fingerprint) return;
    navigator.clipboard.writeText(fp.fingerprint);
    toast.success("Fingerprint copied");
  };

  const StatusIcon = data?.active ? ShieldCheck : ShieldAlert;
  const statusColor = data?.active
    ? data.in_grace
      ? "var(--console-alarm)"
      : "var(--console-online)"
    : "var(--console-rec)";

  return (
    <div
      className="h-full flex flex-col overflow-hidden"
      style={{ background: "var(--console-bg)", color: "var(--console-text)" }}
    >
      {/* Page header bar */}
      <div
        className="flex items-center gap-3 px-4 py-2.5 border-b flex-shrink-0"
        style={{ background: "var(--console-panel)", borderColor: "var(--console-border)" }}
      >
        <div className="flex items-center gap-2">
          <span
            className="w-0.5 h-4 rounded-full flex-shrink-0"
            style={{ background: "var(--console-accent)" }}
          />
          <span
            className="font-telemetry text-xs font-semibold uppercase tracking-widest"
            style={{ color: "var(--console-text)" }}
          >
            License
          </span>
        </div>
      </div>

      <div className="flex-1 min-h-0 overflow-y-auto p-4 md:p-6 space-y-4">
        {isLoading && (
          <p className="font-telemetry text-xs" style={{ color: "var(--console-muted)" }}>
            Loading…
          </p>
        )}

        {/* Status card */}
        <ConsoleCard>
          <div className="flex items-start gap-4">
            <StatusIcon
              className="h-7 w-7 shrink-0 mt-0.5"
              style={{ color: statusColor }}
            />
            <div className="flex-1 min-w-0">
              <div className="flex flex-wrap items-center gap-2 mb-1">
                <span
                  className="font-telemetry text-xs font-semibold uppercase tracking-wide"
                  style={{ color: "var(--console-text)" }}
                >
                  Status
                </span>
                {data?.active && (
                  <span
                    className="font-telemetry text-[10px] px-1.5 py-0.5 rounded border uppercase tracking-wide"
                    style={{
                      background: "rgba(139,92,246,0.1)",
                      borderColor: "rgba(139,92,246,0.3)",
                      color: "#c4b5fd",
                    }}
                  >
                    {data.tier || "—"}
                  </span>
                )}
                {data?.in_grace && (
                  <span
                    className="font-telemetry text-[10px] px-1.5 py-0.5 rounded border"
                    style={{
                      background: "rgba(245,158,11,0.1)",
                      borderColor: "rgba(245,158,11,0.3)",
                      color: "var(--console-alarm)",
                    }}
                  >
                    Grace period
                  </span>
                )}
                {!data?.active && (
                  <span
                    className="font-telemetry text-[10px] px-1.5 py-0.5 rounded border"
                    style={{
                      background: "rgba(239,68,68,0.1)",
                      borderColor: "rgba(239,68,68,0.3)",
                      color: "var(--console-rec)",
                    }}
                  >
                    {reasonLabel(data?.reason)}
                  </span>
                )}
              </div>
              {data?.customer && (
                <p
                  className="font-telemetry text-[11px] mt-0.5"
                  style={{ color: "var(--console-muted)" }}
                >
                  {data.customer} · {data.license_id}
                </p>
              )}
              {data?.expires_at ? (
                <p
                  className="font-telemetry text-[11px] mt-0.5 flex items-center gap-1"
                  style={{ color: "var(--console-muted)" }}
                >
                  <Calendar className="h-3 w-3" />
                  Expires {data.expires_at.slice(0, 10)}
                  {data.days_remaining != null && data.days_remaining >= 0 && (
                    <span
                      style={{
                        color:
                          data.days_remaining <= 30
                            ? "var(--console-alarm)"
                            : "var(--console-muted)",
                      }}
                    >
                      ({data.days_remaining}d remaining)
                    </span>
                  )}
                </p>
              ) : (
                data?.active && (
                  <p
                    className="font-telemetry text-[11px] mt-0.5 flex items-center gap-1"
                    style={{ color: "var(--console-muted)" }}
                  >
                    <Calendar className="h-3 w-3" />
                    Perpetual license
                  </p>
                )
              )}
            </div>
            <div className="flex flex-col gap-2 shrink-0">
              <input
                ref={inputRef}
                type="file"
                accept=".lic,.txt"
                onChange={onPick}
                className="hidden"
              />
              <PrimaryBtn
                onClick={() => inputRef.current?.click()}
                disabled={activateMut.isPending}
              >
                <UploadCloud className="h-3.5 w-3.5 mr-1.5" />
                {activateMut.isPending ? "Activating…" : "Upload license"}
              </PrimaryBtn>
              {data?.active && (
                <SecondaryBtn onClick={() => setConfirmClear(true)}>
                  <Trash2
                    className="h-3.5 w-3.5 mr-1.5"
                    style={{ color: "var(--console-rec)" }}
                  />
                  Remove
                </SecondaryBtn>
              )}
            </div>
          </div>
        </ConsoleCard>

        {/* Hardware fingerprint */}
        <ConsoleCard>
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <Cpu className="h-3.5 w-3.5" style={{ color: "var(--console-muted)" }} />
              <span
                className="font-telemetry text-[10px] uppercase tracking-widest"
                style={{ color: "var(--console-muted)" }}
              >
                Machine fingerprint
              </span>
            </div>
            {data?.fingerprint_match === false && (
              <span
                className="font-telemetry text-[10px] px-1.5 py-0.5 rounded border"
                style={{
                  background: "rgba(239,68,68,0.1)",
                  borderColor: "rgba(239,68,68,0.3)",
                  color: "var(--console-rec)",
                }}
              >
                Mismatch
              </span>
            )}
          </div>
          <div className="flex items-center gap-2 mt-1">
            <code
              className="font-telemetry text-[11px] break-all flex-1"
              style={{ color: "var(--console-text)" }}
            >
              {fp?.fingerprint || data?.fingerprint || "—"}
            </code>
            <SecondaryBtn onClick={copyFingerprint} disabled={!fp?.fingerprint}>
              Copy
            </SecondaryBtn>
          </div>
          <p
            className="font-telemetry text-[10px] mt-2"
            style={{ color: "var(--console-muted)" }}
          >
            Send this to the vendor when requesting a hardware-bound license.
          </p>
        </ConsoleCard>

        {/* Usage */}
        {data?.active && (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <StatBar
              label="Cameras"
              used={data?.usage?.cameras || 0}
              limit={data?.camera_limit || 0}
              icon={Camera}
            />
          </div>
        )}

      </div>

      <ConfirmDialog
        open={confirmClear}
        onConfirm={() => clearMut.mutate()}
        onCancel={() => setConfirmClear(false)}
        isPending={clearMut.isPending}
      />
    </div>
  );
};

export default LicensePage;
