// =============================================================================
// Settings · License — /settings/license
// =============================================================================
// Shows current license status + usage bars. Admin uploads a .lic file
// generated by the vendor signing tool.
// =============================================================================

import React, { useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  ShieldCheck,
  ShieldAlert,
  UploadCloud,
  Trash2,
  Cpu,
  Camera,
  Calendar,
} from "lucide-react";
import { toast } from "sonner";
import {
  getLicense,
  getFingerprint,
  activateLicense,
  clearLicense,
} from "../../api/license";
import { Button } from "../../components/ui/button";
import { Badge } from "../../components/ui/badge";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "../../components/ui/alert-dialog";

const StatBar = ({ label, used, limit, icon: Icon }) => {
  const pct = limit > 0 ? Math.min(100, (used / limit) * 100) : 0;
  const hot = pct >= 90;
  return (
    <div className="rounded-lg border border-border bg-card/40 p-4">
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2 text-xs text-muted-foreground uppercase tracking-wider">
          {Icon && <Icon className="h-3.5 w-3.5" />}
          {label}
        </div>
        <span className={`text-sm font-mono ${hot ? "text-rose-300" : ""}`}>
          {used} / {limit || "∞"}
        </span>
      </div>
      <div className="h-1.5 rounded-full bg-white/5 overflow-hidden">
        <div
          className={hot ? "bg-rose-400 h-full" : "bg-teal-400 h-full"}
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  );
};

const LicensePage = () => {
  const qc = useQueryClient();
  const inputRef = useRef(null);
  const [confirmClear, setConfirmClear] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ["license"],
    queryFn: getLicense,
  });

  const { data: fp } = useQuery({
    queryKey: ["license-fingerprint"],
    queryFn: getFingerprint,
  });

  const activateMut = useMutation({
    mutationFn: activateLicense,
    onSuccess: () => {
      toast.success("License activated");
      qc.invalidateQueries({ queryKey: ["license"] });
    },
    onError: (e) =>
      toast.error(e?.response?.data?.detail || "License activation failed"),
  });

  const clearMut = useMutation({
    mutationFn: clearLicense,
    onSuccess: () => {
      toast.success("License cleared");
      qc.invalidateQueries({ queryKey: ["license"] });
      setConfirmClear(false);
    },
  });

  const onPick = (e) => {
    const f = e.target.files?.[0];
    if (!f) return;
    activateMut.mutate(f);
    e.target.value = "";
  };

  const copyFingerprint = () => {
    if (!fp?.fingerprint) return;
    navigator.clipboard.writeText(fp.fingerprint);
    toast.success("Fingerprint copied");
  };

  const StatusIcon = data?.active ? ShieldCheck : ShieldAlert;
  const statusTone = data?.active
    ? data.in_grace
      ? "text-amber-300"
      : "text-emerald-300"
    : "text-rose-300";

  return (
    <div className="p-4 md:p-6 max-w-5xl space-y-5">
      {/* Status header */}
      <div className="rounded-xl border border-border bg-card/40 p-5">
        <div className="flex items-start gap-4">
          <StatusIcon className={`h-8 w-8 ${statusTone} shrink-0`} />
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <h1 className="text-xl font-semibold">License</h1>
              {data?.active && (
                <Badge className="bg-violet-500/15 text-violet-300 border border-violet-500/30 uppercase">
                  {data.tier || "—"}
                </Badge>
              )}
              {data?.in_grace && (
                <Badge className="bg-amber-500/15 text-amber-300 border border-amber-500/30">
                  Grace period
                </Badge>
              )}
              {!data?.active && (
                <Badge className="bg-rose-500/15 text-rose-300 border border-rose-500/30">
                  {data?.reason === "no_license_installed" ? "No license" : data?.reason || "Inactive"}
                </Badge>
              )}
            </div>
            {data?.customer && (
              <p className="text-sm text-muted-foreground mt-1">
                {data.customer} · {data.license_id}
              </p>
            )}
            {data?.expires_at && (
              <p className="text-xs text-muted-foreground font-mono mt-1 inline-flex items-center gap-1">
                <Calendar className="h-3 w-3" />
                Expires {data.expires_at.slice(0, 10)}
                {data.days_remaining != null && (
                  <span
                    className={
                      data.days_remaining <= 30
                        ? "ml-1 text-amber-300"
                        : "ml-1 text-muted-foreground"
                    }
                  >
                    ({data.days_remaining}d remaining)
                  </span>
                )}
              </p>
            )}
          </div>
          <div className="flex flex-col gap-2 shrink-0">
            <input
              ref={inputRef}
              type="file"
              accept=".lic,.txt"
              onChange={onPick}
              className="hidden"
            />
            <Button
              onClick={() => inputRef.current?.click()}
              disabled={activateMut.isPending}
            >
              <UploadCloud className="h-4 w-4 mr-1" />
              {activateMut.isPending ? "Activating…" : "Upload license"}
            </Button>
            {data?.active && (
              <Button variant="outline" size="sm" onClick={() => setConfirmClear(true)}>
                <Trash2 className="h-3.5 w-3.5 mr-1 text-rose-300" />
                Remove
              </Button>
            )}
          </div>
        </div>
      </div>

      {/* Hardware fingerprint */}
      <div className="rounded-lg border border-border bg-card/40 p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs text-muted-foreground uppercase tracking-wider">
            <Cpu className="h-3.5 w-3.5" />
            Machine fingerprint
          </div>
          {data?.fingerprint_match === false && (
            <Badge className="bg-rose-500/15 text-rose-300 border border-rose-500/30">
              Mismatch
            </Badge>
          )}
        </div>
        <div className="mt-2 flex items-center gap-2">
          <code className="text-xs font-mono break-all flex-1">
            {fp?.fingerprint || data?.fingerprint || "—"}
          </code>
          <Button
            variant="outline"
            size="sm"
            onClick={copyFingerprint}
            disabled={!fp?.fingerprint}
          >
            Copy
          </Button>
        </div>
        <p className="text-[11px] text-muted-foreground mt-2">
          Send this to the vendor when requesting a hardware-bound license.
        </p>
      </div>

      {/* Usage */}
      {data?.active && (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <StatBar
            label="Cameras"
            used={data?.usage?.cameras || 0}
            limit={data?.camera_limit || 0}
            icon={Camera}
          />
        </div>
      )}

      {/* Features */}
      {data?.active && data?.features?.length > 0 && (
        <div className="rounded-lg border border-border bg-card/40 p-4">
          <h3 className="text-xs text-muted-foreground uppercase tracking-wider mb-3">
            Features
          </h3>
          <div className="flex flex-wrap gap-1.5">
            {data.features.map((f) => (
              <Badge
                key={f}
                variant="outline"
                className="text-[10px]"
              >
                {f}
              </Badge>
            ))}
          </div>
        </div>
      )}

      <AlertDialog open={confirmClear} onOpenChange={setConfirmClear}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Remove license?</AlertDialogTitle>
            <AlertDialogDescription>
              The .lic file will be deleted. New cameras above the dev cap
              will be rejected. Upload a new license file to restore
              functionality.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => clearMut.mutate()}
              className="bg-destructive hover:bg-destructive/90"
            >
              Remove
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {isLoading && (
        <p className="text-sm text-muted-foreground">Loading…</p>
      )}
    </div>
  );
};

export default LicensePage;
