"""baseline frs schema

Creates the full FRS schema for a fresh database. Idempotent (checkfirst) so it
is safe on an existing pre-Alembic install — those are stamped to this revision
rather than re-running it. Later schema changes get their own autogenerated
migrations going forward.

Revision ID: 1ddf1568b949
Revises:
Create Date: 2026-06-18
"""
from alembic import op

from db.models import Base

revision = "1ddf1568b949"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(op.get_bind(), checkfirst=True)


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
